add -x|--nolock arg
ns1/pktvisor-v1 pull request #7
Opened 2019-08-28 19:52 UTC by pgray

This adds an arg to pktvisor to not lock memory

2019-08-28 19:59 UTC, tlloydaubry approved these changes

2019-08-28 20:24 UTC, bcavns01 commented on src/pktvisor.c
> +       "  -x|--nolock                    Don't lock memory\n"
That alignment.  You of all people... :disappointed: 

:trollface:

2019-08-28 20:37 UTC, pgray commented on src/pktvisor.c
> +       "  -x|--nolock                    Don't lock memory\n"
Weirdly if you look at the full file it's fine.

2019-08-28 21:08 UTC, elindsey approved these changes

2019-08-28 21:13 UTC, bcavns01 approved these changes

2019-08-28 21:15 UTC, fcelda commented on src/pktvisor.c
> +    case 'x':
Tabs.

2019-08-28 21:16 UTC, fcelda requested changes
Please, fix the indentation to be consistent with surrounding code. Even though the surrounding code is indented strangely. Otherwise LGTM.

2019-08-29 10:32 UTC, fcelda commented on src/pktvisor.c
> +       "  -x|--nolock                    Don't lock memory\n"
@pgray
![Screenshot from 2019-08-29 12-31-34](https://user-images.githubusercontent.com/1205482/63933180-036ebd80-ca59-11e9-88ad-13d8c04afe9a.png)

2019-08-29 13:56 UTC, fcelda approved these changes

2019-08-29 13:57 UTC, merged